package com.example.telegramrm

class ChatProvider {
    companion object{
        val chatList = listOf<Chat>(
            Chat(1,
                "Monkey D. Luffy",
                "Sere el rey de los piratas",
                "https://pm1.aminoapps.com/6075/57f6e4277ab0ec8aa0c748703a01ac5091649b5c_hq.jpg",
                "08:41",
                "un Check",
                1),
            Chat(2,
                "Mark Zuckerberg",
                "Hey bro! come back to whats please",
                "https://images.newrepublic.com/b53d30e509b44bfc5f7bf3d3a03cc000fcd50623.jpeg?w=1200&h=600&crop=faces&fit=crop&fm=jpg",
                "13:59",
                "",
                null),
            Chat(3,
                "Telegram ",
                "Nuevas actualizaciones perronas ...",
                "https://logodownload.org/wp-content/uploads/2017/11/telegram-logo-0-2.png",
                "13:59",
                "un Check",
                1),
            Chat(4,
                "Light Yagami",
                "Oye bro, cual es tu nombre completo :v",
                "https://static.wikia.nocookie.net/deathnote/images/3/33/Light_Yagami_-_Anime.png/revision/latest?cb=20190304212220&path-prefix=es",
                "lun",
                "un Check",
                1),
            Chat(5,
                "Gol D. Roger",
                "Lo deje todo escondido en ese lugar" ,
                "https://static.wikia.nocookie.net/onepiece/images/1/14/Roger_r%C3%ADe_al_encontrar_el_One_Piece.png/revision/latest?cb=20210404102313&path-prefix=es",
                "04 de sept",
                "",
                3),
            Chat(6,
                "Coco Basile",
                "Whisky o champang? ",
                "https://j.gifs.com/KzLGAP.gif",
                "04 de sept",
                "un Check",
                1),
            Chat(7,
                "Naruto Uzumaki",
                "Soy el más perron aqui \uD83D\uDCAA",
                "https://qph.cf2.quoracdn.net/main-qimg-35eb7873be0a78265015a973ac774c02-lq",
                "04 de sept",
                "un Check",
                1),
            Chat(8,
                "Rock Lee",
                "El trabajo duro derrota el talento natural",
                "https://www.mundodeportivo.com/alfabeta/hero/2022/12/Naruto-al-fin-revela-cual-es-el-secreto-de-la-fuerza-de-Rock-Lee.jpg?width=768&aspect_ratio=16:9&format=nowebp",
                "3 de ago",
                "@drawable/visto",
                null),
            Chat(9,
                "Sasuke Uchiha",
                "Restaurare mi clan",
                "https://static.wikia.nocookie.net/naruto/images/2/21/Sasuke_Part_1.png/revision/latest/scale-to-width-down/300?cb=20170716092103",
                "1 de ago",
                "@drawable/doble_visto",
                null),
            Chat(10,
                "Leo Messi \uD83C\uDDE6\uD83C\uDDF7",
                "¡Che! ¿Futbolito hoy? ⚽  necesito tu magia ahí",
                "https://supersport-cms-prod.azureedge.net/media/jqnb1tys/lionel-messi-2023-inaction-g-1200.jpg?width=2048&quality=100",
                "13:59",
                "@drawable/visto",
                null),
            Chat(11,
                "Eren Jaeger",
                "Tatakae Tatakae Tatakae ....",
                "https://i1.sndcdn.com/artworks-J6bKfUY8d3NBoXL2-Vu5rug-t500x500.jpg",
                "10 de jul",
                "un Check",
                1),
            Chat(12,
                "Mikasa Ackerman",
                "Haz visto a Eren ... ",
                "https://i.scdn.co/image/ab67616d0000b2734581668a098a17c03e480726",
                "20 de jun",
                "un Check",
                1),
            Chat(13,
                "Roronoa Zoro",
                "mmmm este no es mi chat",
                "https://c4.wallpaperflare.com/wallpaper/23/617/196/one-piece-roronoa-zoro-1959x1496-anime-one-piece-hd-art-wallpaper-preview.jpg",
                "10.12.21",
                "un Check",
                1),
            Chat(14,
                "Kakashi Hatake",
                "Me perdi en el sendero de la vida",
                "https://static.wikia.nocookie.net/naruto/images/2/2e/Kakashi_Hatake_Parte_I_y_II_Anime.png/revision/latest?cb=20221120050147&path-prefix=es",
                "09.11.21",
                "un Check",
                1),
            Chat(15,
                "Monkey D. Luffy",
                "Sere el rey de los piratas",
                "https://pm1.aminoapps.com/6075/57f6e4277ab0ec8aa0c748703a01ac5091649b5c_hq.jpg",
                "08:41",
                "un Check",
                1),
            Chat(16,
                "Mark Zuckerberg",
                "Hey bro! come back to whats please",
                "https://images.newrepublic.com/b53d30e509b44bfc5f7bf3d3a03cc000fcd50623.jpeg?w=1200&h=600&crop=faces&fit=crop&fm=jpg",
                "13:59",
                "",
                null),
            Chat(17,
                "Telegram ",
                "Nuevas actualizaciones perronas ...",
                "https://logodownload.org/wp-content/uploads/2017/11/telegram-logo-0-2.png",
                "13:59",
                "un Check",
                1),
            Chat(18,
                "Light Yagami",
                "Oye bro, cual es tu nombre completo :v",
                "https://static.wikia.nocookie.net/deathnote/images/3/33/Light_Yagami_-_Anime.png/revision/latest?cb=20190304212220&path-prefix=es",
                "lun",
                "un Check",
                1),
            Chat(19,
                "Gol D. Roger",
                "Lo deje todo escondido en ese lugar" ,
                "https://static.wikia.nocookie.net/onepiece/images/1/14/Roger_r%C3%ADe_al_encontrar_el_One_Piece.png/revision/latest?cb=20210404102313&path-prefix=es",
                "04 de sept",
                "",
                3),
            Chat(20,
                "Coco Basile",
                "Whisky o champang? ",
                "https://j.gifs.com/KzLGAP.gif",
                "04 de sept",
                "un Check",
                1),
            Chat(21,
                "Naruto",
                "Soy el más perron aqui \uD83D\uDCAA",
                "https://qph.cf2.quoracdn.net/main-qimg-35eb7873be0a78265015a973ac774c02-lq",
                "04 de sept",
                "un Check",
                1),
            Chat(22,
                "Rock Lee",
                "El trabajo duro derrota el talento natural",
                "https://www.mundodeportivo.com/alfabeta/hero/2022/12/Naruto-al-fin-revela-cual-es-el-secreto-de-la-fuerza-de-Rock-Lee.jpg?width=768&aspect_ratio=16:9&format=nowebp",
                "3 de ago",
                "@drawable/visto",
                null),
            Chat(23,
                "Sasuke Uchiha",
                "Restaurare mi clan",
                "https://static.wikia.nocookie.net/naruto/images/2/21/Sasuke_Part_1.png/revision/latest/scale-to-width-down/300?cb=20170716092103",
                "1 de ago",
                "@drawable/doble_visto",
                null),
            Chat(24,
                "Leo Messi \uD83C\uDDE6\uD83C\uDDF7",
                "¡Che! ¿Futbolito hoy? ⚽  necesito tu magia ahí",
                "https://supersport-cms-prod.azureedge.net/media/jqnb1tys/lionel-messi-2023-inaction-g-1200.jpg?width=2048&quality=100",
                "13:59",
                "@drawable/visto",
                null),
            Chat(25,
                "Eren Jaeger",
                "Tatakae Tatakae Tatakae ....",
                "https://i1.sndcdn.com/artworks-J6bKfUY8d3NBoXL2-Vu5rug-t500x500.jpg",
                "10 de jul",
                "un Check",
                1),
            Chat(26,
                "Mikasa Ackerman",
                "Haz visto a Eren ... ",
                "https://i.scdn.co/image/ab67616d0000b2734581668a098a17c03e480726",
                "20 de jun",
                "un Check",
                1),
            Chat(27,
                "Roronoa Zoro",
                "mmmm este no es mi chat",
                "https://c4.wallpaperflare.com/wallpaper/23/617/196/one-piece-roronoa-zoro-1959x1496-anime-one-piece-hd-art-wallpaper-preview.jpg",
                "10.12.21",
                "un Check",
                1),
            Chat(28,
                "Kakashi Hatake",
                "Me perdi en el sendero de la vida",
                "https://static.wikia.nocookie.net/naruto/images/2/2e/Kakashi_Hatake_Parte_I_y_II_Anime.png/revision/latest?cb=20221120050147&path-prefix=es",
                "09.11.21",
                "un Check",
                1),
        )

        fun getChatById(chatId: Int): Chat? {
            return chatList.find { it.id == chatId }
        }
    }
}